dist: bionic
language: python

git:
  depth: false

stages:
  - black
  - flake8
  - patterns
  - test

jobs:
  include:
    - stage: "black"
      python: "3.6"
      env: BLACK=20.8b1
      install: pip install black==$BLACK
      script: black phone_gen dev_tools --check
      after_success: false
    - stage: "flake8"
      python: "3.6"
      env:
        - FLAKE8=3.8.3
        - PEP8_NAMING=0.11.1
      install:
        - pip install flake8==$FLAKE8
        - pip install pep8-naming==$PEP8_NAMING
      script: flake8 phone_gen dev_tools
      after_success: false
    - stage: "patterns"
      python: "3.6"
      env: LIBPHONENUMBER=v8.8.8
      install: pip install -U requests
      script:
        - python dev_tools/patterns_generator.py --tag=$LIBPHONENUMBER
        - pip install -e .
        - phone-gen --version
      after_success: false
env:
  - PHONENUMBERS="8.12.9"  # last version

python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install phonenumbers==$PHONENUMBERS
  - pip install pytest-cov==2.10.1
  - pip install pytest==6.0.1
  - pip install -e .
script:
  - pip freeze | grep phonenumbers
  - pytest tests


deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: bdist_wheel --universal
  on:
    tags: true
    repo: tolstislon/phone-gen
    python: "3.8"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always